### ISSUE TITLE
Fail: glyphs swapping

### ISSUE THREAD

**Issue by vv-monsalve** [TypeTogether/Playpen-Sans#24]
@josescaglione, @casasin 

Edit: I'll create a separate issue for each fail.

<details>
    <summary>🔥 <b>FAIL</b> Ensure the font supports case swapping for all its glyphs. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/universal.glyphset.html#"></a></summary>
    <div>
> 
> Ensure that no glyph lacks its corresponding upper or lower counterpart
> (but only when unicode supports case-mapping).
> 

> Original proposal: https://github.com/googlefonts/fontbakery/issues/3230

* 🔥 **FAIL** <p>The following glyphs lack their case-swapping counterparts:</p>
<table>
<thead>
<tr>
<th align="left">Glyph present in the font</th>
<th align="left">Missing case-swapping counterpart</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left">U+1E5F: LATIN SMALL LETTER R WITH LINE BELOW</td>
<td align="left">U+1E5E: LATIN CAPITAL LETTER R WITH LINE BELOW</td>
</tr>
</tbody>
</table>
 [code: missing-case-counterparts]

</div>
</details>

**Comment by casasin** [comment]
They're both there, problem was that Rmacronbelow was not decomposed. Check in the last version. I think this should not be reported anymore.

**Comment by josescaglione** [comment]
Ran FB. Not reported

**Comment by vv-monsalve** [comment]
> I think this should not be reported anymore.

Great, I'll pull the latest files and let you know.

**Comment by vv-monsalve** [comment]
After pulling the latest files at commit `8ae1e84` this is no longer reported
