### ISSUE TITLE
Fail: Check glyphs do not have components which are themselves components

### ISSUE THREAD

**Issue by vv-monsalve** [TypeTogether/Playpen-Sans#26]
@casasin They could use a new component or perhaps could be decomposed at the end of the process.  

<details>
    <summary>🔥 <b>FAIL</b> Check glyphs do not have components which are themselves components. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/googlefonts.glyf.html#"></a></summary>
    <div>

> 
> There have been bugs rendering variable fonts with nested components.
> Additionally, some static fonts with nested components have been reported
> to have rendering and printing issues.
> 
> For more info, see:
> * https://github.com/fonttools/fontbakery/issues/2961
> * https://github.com/arrowtype/recursive/issues/412
> 

> Original proposal: https://github.com/fonttools/fontbakery/issues/2961

* 🔥 **FAIL** <p>The following glyphs have components which themselves are component glyphs:
* Oslashacute
* emacrongrave
* oslashacute
* Ve-cy.alt6
* Iegrave-cy
* Io-cy
* Ka-cy.alt3
* Kje-cy
* Em-cy.alt5
* Em-cy.alt6
* En-cy.alt5
* En-cy.alt6
* Es-cy.alt5
* Es-cy.alt6
* iigrave-cy
* ha-cy.alt3
* Ustraight-cy.alt5
* Ustraight-cy.alt6
* a-cy.ss01.alt4
* a-cy.ss01.alt5
* a-cy.ss01.alt6
* u-cy.ss01.alt4
* u-cy.ss01.alt5
* u-cy.ss01.alt6
* Beta
* Zeta.alt3
* Zeta.alt4
* Eta
* Eta.alt1
* Kappa.alt5
* Mu.alt4
* Mu.alt5
* Upsilon.alt3
* Upsilon.alt4
* Alphatonos
* Epsilontonos
* Etatonos
* Iotatonos
* Omicrontonos
* Upsilontonos
* Iotadieresis
* Upsilondieresis
* omicrontonos
* Mu.ss01.alt3
* Mu.ss01.alt4
* Mu.ss01.alt5
* alphatonos.ss01
* yodhiriq-hb
* yodhiriq-hb.JII
* shinshindot-hb
* shinsindot-hb
* shindageshshindot-hb
* shindageshsindot-hb
* hatafsegol-hb
* hatafsegol-hb
* hatafpatah-hb
* hatafqamats-hb
* segol-hb
* qubuts-hb
* qubuts-hb
* qubuts-hb
* alefHamzabelow-ar
* alefHamzabelow-ar.fina
* beh-ar
* beh-ar.fina
* beh-ar.medi
* beh-ar.init
* jeem-ar
* jeem-ar.fina
* jeem-ar.medi
* jeem-ar.init
* kehehThreedotsabove-ar.medi
* kehehThreedotsabove-ar.init
* lamVabove-ar
* lamVabove-ar.init
* lamVabove-ar.medi
* lamVabove-ar.fina
* tehMarbutagoal-ar
* oe-ar
* oe-ar.fina
* yeh-ar
* yeh-ar.fina
* yeh-ar.medi
* yeh-ar.init
* yehVabove-ar
* yehVabove-ar.fina
* yehVabove-ar.medi
* yehVabove-ar.medi
* yehVabove-ar.init
* yehVabove-ar.init
* yehFarsi-ar.medi
* yehFarsi-ar.init
* lam_alefHamzabelow-ar
* lam_alefHamzabelow-ar.fina
* feh_yeh-ar
* qaf_yeh-ar
* perthousand-ar
* hamzaaboveFathatan-ar
* hamzabelowKasra-ar
* hamzabelowKasra-ar
* hamzabelowKasratan-ar
* hamzabelowKasratan-ar
* kasratan-ar
* shaddaFathatan-ar
* shaddaKasratan-ar
* ai_anusvara-deva
* ai_anusvara-deva.alt1
* ai_anusvara-deva.alt2
* ai_anusvara-deva.alt3
* ai_candraBindu-deva
* ai_candraBindu-deva.alt1
* ai_candraBindu-deva.alt2
* ai_candraBindu-deva.alt3
* o-deva.alt1
* o-deva.alt2
* o-deva.alt3
* o_anusvara-deva.alt1
* o_anusvara-deva.alt1
* o_anusvara-deva.alt2
* o_anusvara-deva.alt2
* o_anusvara-deva.alt3
* o_anusvara-deva.alt3
* o_candraBindu-deva.alt1
* o_candraBindu-deva.alt1
* o_candraBindu-deva.alt2
* o_candraBindu-deva.alt2
* o_candraBindu-deva.alt3
* o_candraBindu-deva.alt3
* au-deva.alt1
* au-deva.alt2
* au-deva.alt3
* au_anusvara-deva.alt1
* au_anusvara-deva.alt1
* au_anusvara-deva.alt2
* au_anusvara-deva.alt2
* au_anusvara-deva.alt3
* au_anusvara-deva.alt3
* au_candraBindu-deva.alt1
* au_candraBindu-deva.alt1
* au_candraBindu-deva.alt2
* au_candraBindu-deva.alt2
* au_candraBindu-deva.alt3
* au_candraBindu-deva.alt3
* oMatra_anusvara-deva
* oMatra_anusvara-deva.alt1
* oMatra_anusvara-deva.alt2
* oMatra_anusvara-deva.alt3
* oMatra_candraBindu-deva
* oMatra_candraBindu-deva.alt1
* oMatra_candraBindu-deva.alt2
* oMatra_candraBindu-deva.alt3
* auMatra_anusvara-deva
* auMatra_anusvara-deva.alt1
* auMatra_anusvara-deva.alt2
* auMatra_anusvara-deva.alt3
* auMatra_candraBindu-deva
* auMatra_candraBindu-deva.alt1
* auMatra_candraBindu-deva.alt2
* auMatra_candraBindu-deva.alt3
* dddh-deva
* dddh-deva.alt1
* dddh-deva.alt2
* dddh-deva.alt3
* rh-deva
* rh-deva.alt1
* rh-deva.alt2
* rh-deva.alt3
* l_za-deva
* l_fa-deva
* sh_qa-deva
* s_k_va-deva
* s_t_ya-deva
* q_qa-deva
* khh_ta-deva
* khh_ma-deva
* khh_va-deva
* khh_sha-deva
* khh_sha-deva.loclMAR
* z_ba-deva and oslashacute.BRACKET.varAlt01</p>
 [code: found-nested-components]

</div>
</details>

**Comment by casasin** [comment]
This has been fixed in v1.012 (not reported anymore) by using fontmake's `--flatten-components` option.

**Comment by vv-monsalve** [comment]
After pulling the latest files at commit `8ae1e84` this is no longer reported
