### ISSUE TITLE
Icons names + Syntax

### ISSUE THREAD

**Issue by vv-monsalve** [TypeTogether/Playpen-Sans#3]
- Access to icons through `calt` feature with syntax `<container>'icon-name'</container>` 
e.g.: `[:puzzle:]` for "puzzle" icon
- Icon names ideally should be simple and meaningful 
- Instructions should be included in the Readme.md file

Proposal for names to make them easy to remember/use:
- using a hyphen instead of camel case names
- use words that convey meaningful ideas or concepts instead of graphic descriptions
- keeping a unified structure in composed names like descriptor-noun, making adjectives first as in English use e.g. happy-sun; pirate-sun

Icons list with current names and names suggestions

| glyph Name           | uni | | Proposed name |
|---|---|---|---|
| shootingStar         | 1F320 |  🌠 | shooting-star |
| birthdayCake         | 1F382 |  🎂 | birthday-cake |
| artistPalette        | 1F3A8 |  🎨 | paint |
| whiteUpBackhandIndex | 1F446 |  👆 | attention-index |
| thumbsUpSign         | 1F44D |  👍 | thumbs-up |
| thumbsDownSign       | 1F44E |  👎 | thumbs-down |
| openBook             | 1F4D6 |  📖 | read |
| cheeringMegaphone    | 1F4E3 |  📣 | announcement |
| battery              | 1F50B |  🔋 | battery |
| unicornFace          | 1F984 |  🦄 | unicorn |
| dinosaur             | None | 🦖 | dinosaur |
| jigsawPuzzlePiece    | 1F9E9 |  🧩 | puzzle |
| ringedPlanet         | 1FA90 |  🪐 | planet |
| pencil               | 270F | ✏ | pencil |
| checkmark            | 2713 |   ✓ | check-mark |
| crossMark            | 274C |   ❌ | cross-mark |
| roundTarget          | 1F78B | 🎯 | target |
| sunFace              | 1F31E |  🌞 | happy-sun |
| suninlove            | None | | loving-sun |
| sunpirate            | None | | pirate-sun |
| sunsad               | None | | sad-sun |
| sunwink              | None | | wink-sun |
| homework             | None | | homework |
| paperplane           | None |  | paper-plane |
| pencilbook           | None | | write |
| reward               | None | | accomplishment |

**Comment by chrissimpkins** [comment]
Our subsetter removes encoded icons and we're seeing tofu in sandbox.  Working with Nate to update the subsetter definition for this family so that we don't strip the icons out.

**Comment by vv-monsalve** [comment]
I created a [spreadsheet for the icons](https://docs.google.com/spreadsheets/d/1Kg2LQBoTcW7uip-T5fyLF4xEdJqonyYQZo5s8NZnkTI/edit#gid=0) with the information from the above table. When doing so I noticed we should probably be using [1F3AF](https://www.google.com/url?q=https://www.compart.com/en/unicode/U%2B1F3AF&sa=D&source=editors&ust=1695079979695082&usg=AOvVaw0ctOk38rlrZk7wotJVz5z2) instead of https://www.compart.com/en/unicode/U+1F78B for the `round-target` icon

**Comment by vv-monsalve** [comment]
We reviewed this today with José and agreed on using  `1F3AF`.
@casasin Could you please update it to

````
| directHit          | 1F3AF |  🎯 | on-target | perfect |
````

**Comment by casasin** [comment]
Done in `a2ffdcd`

**Comment by vv-monsalve** [comment]
Thanks @casasin. I've pulled and tested it in InDesign and is working fine. 
The version number must be increased though, to register the change from the one that was already included in our servers. Please change it to `1.001`.

**Comment by casasin** [comment]
Changed already in `de384a1`

**Comment by vv-monsalve** [comment]
The last decision made on this subject was to rename the icons to emojis and to discard the `calt` replacements in favor of assigning codepoints to all the emojis.

The v1.002 fonts already include this change, and the #12 is updating the Readme with the defined codepoints.

So, I'm closing this issue here. Please feel free to reopen it if you consider it should be kept open for any reason.
