### ISSUE TITLE
ccmp code change and vertical metrics

### ISSUE THREAD

**Issue by josescaglione** [TypeTogether/Playpen-Sans#4]
As a result of the discussion regarding the vertical metrics we had with @vv-monsalve  I tightened the double accents in Pinyin and Viet glyphs. Additionally I replaced our default **y** by **y.ss01** in the **ydotbelow** glyph, which saves lots of vertical space as it was the deepest character in the font.

In order for the randomizer to work correctly the ccmp entry for **ydotbelow** must be changed from
`    sub ydotbelow by y dotbelowcomb;
`
to:
`    sub ydotbelow by y.ss01 dotbelowcomb;
`

**Comment by casasin** [comment]
@vv-monsalve : the repo is now public.

**Comment by vv-monsalve** [comment]
Thank you
